name: Generate Work Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-docx tqdm

    - name: Run script to generate report for prac1
      run: python src/report.py

    - name: Upload report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: work-report
        path: work_report.docx
